name: CA

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: perform lint
        run: |
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOBIN
          make req lint
