name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: install pre-requisite
      run:  |
        wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
        source /etc/lsb-release
        echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
        sudo apt-get update
        sudo apt-get install influxdb
        sudo service influxdb start
    - name: test
      run: make test
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
